language: python
python:
   - "2.7"
services:
  - docker
before_install:
  - make image
install:
  - pip install python-coveralls
script:
  - make test-image
  - make test
git:
  submodules: false

after_success:
  - coveralls --data-file builder/test/coverage.xml
