language: python
python:
   - "3.6"
services:
  - docker
before_install:
  - echo -e "machine github.com\n  login $GITHUB_API_TOKEN" >> ~/.netrc
  - sed -i "s/git@github.com:/https:\/\/github.com\//" .gitmodules
  - git submodule update --init --recursive
  - make image
install:
  - pip install python-coveralls
script:
  - make test
git:
  depth: 3
  submodules: false

after_success:
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_PULL_REQUEST" == "false" ) ]]; then
    coveralls;
    make deploy;
    fi
