language: python
python:
   - "3.6"
services:
  - docker
before_install:
  - echo -e "machine github.com\n  login $GITHUB_API_TOKEN" >> ~/.netrc
  - sed -i "s/git@github.com:/https:\/\/github.com\//" .gitmodules
  - git submodule update --init --recursive
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - make image
install:
  - pip install python-coveralls
script:
  - make test
git:
  depth: 3
  submodules: false

after_success:
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) && ( "$TRAVIS_PULL_REQUEST" == "false" ) ]]; then
    coveralls;
    make deploy;
    fi
